# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app
# Copy project files
COPY package.json ./
# If you have a package-lock.json, uncomment the next line
# COPY package-lock.json ./
COPY scripts ./scripts
COPY src ./src
# Install dependencies and build
RUN npm install && npm run build

# ---- Final image ----
FROM node:lts-alpine
WORKDIR /app
# Copy dist and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# Expose no ports; uses stdio
ENTRYPOINT ["node", "dist/cli.js"]
